### ISSUE TITLE
rendering plantuml content

### ISSUE THREAD

**Issue by RobertoFioravanti** [exalted/mdwiki-seed#19]
It would be nice to have a Plantuml rendering the content

```plantuml
@startuml component
actor client
node app
database db

db -> app
app -> client
@enduml
````
in this way 

![image](https://github.com/exalted/mdwiki-seed/assets/133392154/77b3b6cd-9834-462d-8fba-eae4f6e6fb6d)

I think it can be handled  by javascript in `index.html` e.g.
[plantuml-code-highlight](https://gitea.com/davidsvantesson/plantuml-code-highlight)

(I tried but without success. But I'm not an expert)

**Comment by exalted** [comment]
@RobertoFioravanti, thanks for the issue. It would've been better to open an issue at https://github.com/Dynalon/mdwiki; however, apparently, MDwiki is not maintained for a while now, so I wouldn't hold my breath expecting this to be implemented any time soon. Closing this issue, and I hope you won't mind! 🙏
