### ISSUE TITLE
Add "title" to config.json

### ISSUE THREAD

**Issue by almereyda** [exalted/mdwiki-seed#4]
It would be nice to include the `title` property into the `config.json` template so it's easier to give a custom name to a site.

**Comment by exalted** [comment]
@almereyda thank you for issuing this, but as far as i know there's no `title` property that can be defined `config.json`. Please see [here](http://dynalon.github.io/mdwiki/#!customizing.md) and feel free to reopen this issue if you think I am mistaken.

**Comment by almereyda** [comment]
I am using the `title` property on three sites:
- https://github.com/gartenkarte/gartenkarte.de
- https://github.com/ouisharelabs/hacks
- https://github.com/14mmm/OKFestMMM/tree/gh-pages/en

Consider using http://5minfork.com/ for checking if it works.

It is also mentionned in the official example at https://github.com/Dynalon/mdwiki/blob/gh-pages/config.json . Choose for yourself, as I am not the maintainer of this repository.

**Comment by exalted** [comment]
@almereyda could you please show me how it is actually used in either one of those sites you mentioned? I see you did set the `title` property in `config.json` file, but then I couldn't actually figure out how that is effectively being used anywhere? Thank you/

**Comment by almereyda** [comment]
`title` will be used to render `<title>{title}</title>` as one might expect.

**Comment by exalted** [comment]
@almereyda I totally get it, trust me; but could you please send me a link to the code either one of the repositories you mentioned above uses the `{title}` attribute?

**Comment by almereyda** [comment]
There you go : https://github.com/Dynalon/mdwiki/blob/7958ff3ff6c853fa93adaf21a58db35793c37b32/js/basic_skeleton.js#L26-L41
